apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  annotations:
    mia-platform.eu/version: 14.2.1
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/version: v1.32.1
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: frengo-ale-github
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: DEV
    mia-platform.eu/tenant: 6b38a8ec-816c-487c-986d-c59edb294ea6
spec:
  type: ClusterIP
  ports:
    - name: frontend
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: null
    - name: backoffice
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: null
    - name: admin
      protocol: TCP
      port: 9901
      targetPort: 9901
      nodePort: null
  selector:
    app: api-gateway
