apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  annotations:
    mia-platform.eu/version: 14.2.1
  labels:
    app: authorization-service
    app.kubernetes.io/name: authorization-service
    app.kubernetes.io/version: 2.4.2
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: frengo-ale-github
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: DEV
    mia-platform.eu/tenant: 6b38a8ec-816c-487c-986d-c59edb294ea6
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: null
  selector:
    app: authorization-service
