apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-service
  annotations:
    mia-platform.eu/version: 14.2.1
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    fluentbit.io/parser: pino
  labels:
    app: authorization-service
    app.kubernetes.io/name: authorization-service
    app.kubernetes.io/version: 2.4.2
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: frengo-ale-github
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: DEV
    mia-platform.eu/tenant: 6b38a8ec-816c-487c-986d-c59edb294ea6
    mia-platform.eu/log-type: mia-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-service
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        fluentbit.io/parser: pino
      labels:
        app: authorization-service
        app.kubernetes.io/name: authorization-service
        app.kubernetes.io/version: 2.4.2
        app.kubernetes.io/component: custom
        app.kubernetes.io/part-of: frengo-ale-github
        app.kubernetes.io/managed-by: mia-platform
        mia-platform.eu/stage: DEV
        mia-platform.eu/tenant: 6b38a8ec-816c-487c-986d-c59edb294ea6
        mia-platform.eu/log-type: mia-json
    spec:
      imagePullSecrets:
        - name: nexus-gcloud
      terminationGracePeriodSeconds: 30
      serviceAccountName: authorization-service
      containers:
        - name: authorization-service
          image: nexus.mia-platform.eu/core/authorization-service:2.4.2
          imagePullPolicy: Always
          resources:
            limits:
              memory: 80Mi
              cpu: 100m
            requests:
              memory: 20Mi
              cpu: 10m
          volumeMounts:
            - name: authorization-service-config
              mountPath: /configs
              readOnly: true
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          args: []
          env:
            - name: LOG_LEVEL
              value: 'debug'
            - name: HTTP_PORT
              value: '3000'
            - name: CONFIGURATION_PATH
              value: /configs
            - name: CONFIGURATION_FILE_NAME
              value: auth
            - name: BACKOFFICE_HEADER_KEY
              value: isbackoffice
            - name: SERVICE_VERSION
              value: 2.0.2
            - name: USERINFO_URL
              value: http://auth-flow/userinfo
            - name: CUSTOM_USER_ID_KEY
              value: userId
            - name: HEADERS_TO_PROXY
              value: userId
            - name: AUTHORIZATION_STRICT_MODE_ENABLED
              value: 'true'
            - name: USER_PROPERTIES_TO_PROXY
              value: userId
            - name: CLIENT_TYPE_HEADER_KEY
              value: client-type
            - name: CUSTOM_PERMISSIONS_KEY
              value: permissions
            - name: AUTHORIZATION_HEADERS_TO_PROXY
              value: userId
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: http
              path: /-/ready
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: http
              path: /-/healthz
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      volumes:
        - name: authorization-service-config
          configMap:
            name: authorization-service-config
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
