apiVersion: v1
kind: Service
metadata:
  name: echo-server-2
  annotations:
    mia-platform.eu/version: 14.2.1
  labels:
    app: echo-server-2
    app.kubernetes.io/name: echo-server-2
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: frengo-ale-github
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: DEV
    mia-platform.eu/tenant: 6b38a8ec-816c-487c-986d-c59edb294ea6
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: null
  selector:
    app: echo-server-2
